services:
  frontend:
    container_name: "ilias-docker-training-staging"
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        BUILD_ENV: "staging"
        VITE_SERVER_URL: "http://localhost:8081"
    restart: unless-stopped
    ports:
      - "3001:80"

  backend:
    container_name: "ilias-docker-training-backend-staging"
    build:
      context: .
      dockerfile: server/Dockerfile
    restart: unless-stopped
    ports:
      - "8081:8080"
    volumes:
      - planets-data-staging:/app/data

volumes:
  planets-data-staging:
